/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/Button/Button.vue')['default']
    DateRangeSelect: typeof import('./../src/components/DateRangeSelect/DateRangeSelect.vue')['default']
    FromInput: typeof import('./../src/components/Input/fromInput.vue')['default']
    Hcaptcha: typeof import('./../src/components/Hcaptcha/hcaptcha.vue')['default']
    MultipleSelect: typeof import('./../src/components/MultipleSelect/MultipleSelect.vue')['default']
    NoGameImg: typeof import('./../src/components/NoGameImg/NoGameImg.vue')['default']
    Notify: typeof import('./../src/components/Notify/Notify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleSelect: typeof import('./../src/components/SingleSelect/SingleSelect.vue')['default']
    SvgIcon: typeof import('./../src/components/svgIcon/index.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VantImage: typeof import('vant/es')['tImage']
    VantLazyImg: typeof import('./../src/components/vant/VantLazyImg.vue')['default']
    VantList: typeof import('./../src/components/vant/VantList.vue')['default']
    VantListW: typeof import('./../src/components/vant/VantListW.vue')['default']
    VantNavBar: typeof import('./../src/components/vant/VantNavBar.vue')['default']
    VantPicker: typeof import('./../src/components/vant/VantPicker.vue')['default']
    VantTabs: typeof import('./../src/components/vant/VantTabs.vue')['default']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
